### ISSUE TITLE
Mailing list archive pages all missing/404?

### ISSUE THREAD

**Issue by justinclift** [OpenIndiana/website#18]
(Wasn't sure where to create this issue, but figured the website project probably isn't too far off)

When looking for the OpenIndiana mailing list archives, every one of the mailman links points to pages which are 404:

* https://openindiana.org/mailman/listinfo/mailman -> https://openindiana.org/pipermail/mailman/ (404)
* https://openindiana.org/mailman/listinfo/oi-dev -> https://openindiana.org/pipermail/oi-dev/ (404)
* https://openindiana.org/mailman/listinfo/openindiana-discuss -> https://openindiana.org/pipermail/openindiana-discuss/ (404)
* https://openindiana.org/mailman/listinfo/openindiana-announce -> https://openindiana.org/pipermail/openindiana-announce/ (404)

I was looking for the archives in order to gauge project activity and figure out whether or not to try out OpenIndiana.  (I used to use Solaris years ago...)

**Comment by Toasterson** [comment]
Hi,

Thanks for the contribution. Since this is on the same nginx server that is the correct place to report it :)

I fixed it. I'll send out an announcement for this weeks CoWorking session soon would love to have you there. We are always in need for new contributors.

**Comment by justinclift** [comment]
Thanks, verifying now and yep, they'll all there. :smile:

The CoWorking thing is an interesting idea, but let me try OI out a bit first for a while and see how it goes. :grin:
