### ISSUE TITLE
Broken links on the new OpenIndiana Website

### ISSUE THREAD

**Issue by domag02** [OpenIndiana/website#4]
Some links on [Community page](https://github.com/OpenIndiana/website/blob/main/src/pages/community.md) points to non-existent pages (HTTP error 404):
1. issue tracker:
line 63: `[issue tracker](//www.openindiana.org/bugs).`
2. all of the mailing list links:
line 14: `[mailing lists](https://openindiana.org/mailman/listinfo/)`
line 35: `[oi-dev](https://openindiana.org/mailman/listinfo/oi-dev)`
line 71: `[lists](https://www.openindiana.org/mailman)`
line 73: `[openindiana-announce](https://openindiana.org/mailman/listinfo/openindiana-announce)`
line 74: `[openindiana-discuss](https://openindiana.org/mailman/listinfo/openindiana-discuss)`
line 75: `[oi-dev](https://openindiana.org/mailman/listinfo/oi-dev)`

**Comment by Toasterson** [comment]
Thanks for the info. I fixed the issue tracker link but still need to find a way to make the mailman links work in the current setup. Public mail archive under https://www.mail-archive.com/openindiana-discuss@openindiana.org/ still work

**Comment by domag02** [comment]
OK, thanks.

**Comment by Toasterson** [comment]
With the recent changes to the infrastructure we now have mailman available again on those links. Thus closing this issue as solved.
